site_name: R329

nav:
  - index.md
  - getsource.md
  - r329_evb5.md
  - '编写文档':
    - writting_docs/writting_in_markdown.md
    - writting_docs/embedding_images.md
  - navigation.md



copyright: Copyright &copy; 2020 Allwinner Tech


extra_css:
  - assets/css/style.css

extra_javascript:
  - assets/js/script.js


theme:
  name: material
  language: zh
  logo: assets/img/logo_w.png
  palette:
    primary: blue
    accent: blue
  plugins:
    - search:
      lang: ja
  features:
    - navigation.expand
  
